---
- name: "install nodejs and npm dependencies"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes


- name: "Install pm2"
  become: yes
  npm:
    mame: pm2
    global: yes